#!/usr/bin/python3
import sys
import os

from flake8.main import git

if __name__ == '__main__':
    test_executor = 'python3 -m unittest discover '
    os.popen(f'{test_executor}. "*_tests.py"')
    sys.exit(
        git.hook(
            strict=git.config_for('strict'),
            lazy=git.config_for('lazy'),
        )
    )
